vich_uploader:
    db_driver: orm

    mappings:
        townHall:
            uri_prefix: /images/townHall
            upload_destination: '%kernel.project_dir%/public/images/townHall'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
