vich_uploader:
  db_driver: orm

  mappings:
    townHall:
      uri_prefix: /images/townHall
      upload_destination: "%kernel.project_dir%/public/images/townHall"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

      inject_on_load: false
      delete_on_update: false
      delete_on_remove: false

    article:
      uri_prefix: /images/article
      upload_destination: "%kernel.project_dir%/public/images/article"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

      inject_on_load: false
      delete_on_update: false
      delete_on_remove: false

    structure:
      uri_prefix: /images/structure
      upload_destination: "%kernel.project_dir%/public/images/structure"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

      inject_on_load: false
      delete_on_update: false
      delete_on_remove: false
